"""Attendance refinement

Revision ID: 0349a7c03f1e
Revises: 406559abdc9d
Create Date: 2024-11-26 14:06:46.406243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0349a7c03f1e'
down_revision: Union[str, None] = '406559abdc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_id', table_name='attendance')
    op.drop_column('attendance', 'status')
    op.drop_index('ix_children_id', table_name='children')
    op.drop_constraint('children_attendance_id_fkey', 'children', type_='foreignkey')
    op.drop_column('children', 'attendance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('attendance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('children_attendance_id_fkey', 'children', 'attendance', ['attendance_id'], ['id'])
    op.create_index('ix_children_id', 'children', ['id'], unique=False)
    op.add_column('attendance', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_attendance_id', 'attendance', ['id'], unique=False)
    # ### end Alembic commands ###
