"""Add new tables or changes description

Revision ID: 9d89bc17dd4e
Revises: d17f28a8565e
Create Date: 2024-11-26 13:18:55.740064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d89bc17dd4e'
down_revision: Union[str, None] = 'd17f28a8565e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'date')
    # ### end Alembic commands ###
