"""Attendance refinement

Revision ID: d8fd10a7081a
Revises: 0349a7c03f1e
Create Date: 2024-11-26 14:09:44.869819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fd10a7081a'
down_revision: Union[str, None] = '0349a7c03f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'status')
    # ### end Alembic commands ###
